### ISSUE TITLE
onFailure displaying automatically in console

### ISSUE THREAD

**Issue by WeiPhil** [ohansemmanuel/fake-medium#1]
Hi, I just noted that in the function `actions/index.js` you have specified a onFailure function equal to `console.log("Error occured loading articles")` , I suppose what you meant there is an arrow function like this ? : `() => { console.log("Error occured loading articles"); }` So that IF there is an error that lambda function is called.
Really nice tutorial, it helped me a lot!
Best, Phil

**Comment by ohansemmanuel** [comment]
Hello @WeiPhil You're right. I'll fix this now. 

Apologies for the late reply. Didn't seem to get notified about this issue.
